Don't cordon the master nodes
openshift/kubernetes pull request #1126
Opened 2022-01-20 00:28 UTC by ravisantoshgudimetla

Master nodes already have `master` taint which
cannot be tolerated by normal workloads. If we manually
cordon the master nodes again, some of the control plane
components cannot get rescheduled unless they have
toleration to the `node.kubernetes.io/unschedulable`
taint. Even if we have the toleration in the pod
spec, because of the backwards compability issues
scheduler will ignore nodes which have `unschedulable`
field set. IOW:

- Cordoning master nodes is redundant as masters already
  have taints
- Cordoning master nodes can cause issues which are hard
  to debug as control-plane components may be evicted/preempted
  during e2e run(highly unlikely but a possibility).

So, let's stop cordoning master nodes.

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
cc @wking @soltysh

2022-01-20 04:14 UTC, ravisantoshgudimetla commented
Serial and conformance tests passed.

/retest

2022-01-20 11:53 UTC, soltysh requested changes
/hold
I'd like to see a clear answer why we need to drop the cordoning, although I agree with the approach, we still managed to land k8s bump. So I'd prefer to understand what has changed between last week and now that suddenly affects us.

2022-01-20 15:25 UTC, ravisantoshgudimetla commented
https://github.com/operator-framework/operator-marketplace/pull/458 perhaps introduced the change of certified, redhat and community operators to land on master nodes. The serial test cordons the master nodes which makes it impossible for those operators to land on master nodes.

2022-01-20 15:29 UTC, ravisantoshgudimetla commented
/bugzilla refresh

2022-01-20 16:25 UTC, ravisantoshgudimetla commented
/hold cancel

/retest

2022-01-20 18:48 UTC, ravisantoshgudimetla commented
upgrade passed  as well.

2022-01-20 21:23 UTC, ravisantoshgudimetla commented
/retest

2022-01-21 00:13 UTC, ravisantoshgudimetla commented
/retest

2022-01-21 08:16 UTC, jsafrane commented
Ignore CSI errors, they wait for https://github.com/openshift/kubernetes/pull/1119, which in turn waits for this PR.
Please follow `verify-commits` suggestions, I think it does not like `Bugzilla XYZ:` in the commit message. Retest will not help.

2022-01-21 19:12 UTC, soltysh commented
/close
this merged in https://github.com/openshift/kubernetes/pull/1129

2022-01-21 19:12 UTC, closed without merging