OCPBUGS-17417 pull newer busybox from docker upstream can be updated.
openshift/kubernetes pull request #1666
Opened 2023-08-15 01:07 UTC by jaypoulz

#### What type of PR is this?
/kind bug
/kind failing-test
/kind regression

#### What this PR does / why we need it:
This PR is a temporary workaround to update the busybox image used for in our e2e tests. We determined that the current image fails to deploy when running in a privileged context with selinuxuser_execmod=off. We will try to get this accepted upstream by backporting: https://github.com/kubernetes/kubernetes/pull/119636#issuecomment-1678231294

#### Which issue(s) this PR fixes:
Fixes OCPBUGS-17417

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
```release-note
None
```

2023-08-15 01:11 UTC, jaypoulz commented
/jira refresh

2023-08-15 13:43 UTC, jaypoulz commented
/jira refresh

2023-08-15 13:44 UTC, jaypoulz commented
/jira refresh

2023-08-15 13:46 UTC, jaypoulz commented
/retest required

2023-08-15 18:32 UTC, jaypoulz commented
/retest-required

2023-08-15 19:03 UTC, jaypoulz commented
/retest-required

2023-08-16 08:47 UTC, soltysh requested changes
The commit needs to be named:
`UPSTREAM: 119636: update the busybox test image to 1.36.1` 
to allow us to properly include it in bumps

2023-08-16 08:47 UTC, soltysh commented on test/utils/image/manifest.go
> +	configs[BusyBox] = Config{list.DockerLibraryRegistry, "busybox", "1.36.1"}
I haven't seen that change in upstream, so why do we need it?

2023-10-11 17:26 UTC, jaypoulz commented
No longer needed. Fixed upstream.

2023-10-11 17:26 UTC, closed without merging