OCPBUGS-29437: RPM: Split apiserver, scheduler, k-c-m, kubelet into subpackages
openshift/kubernetes pull request #1882
Opened 2024-02-13 19:49 UTC by sdodson

This change should allow us to install a much smaller set of binaries into RHCOS while preserving functional compatibility with with anyone who installs `openshift-hyperkube` today as it requires all sub packages. Those wishing to have just the kubelet can begin installing `openshift-hyperkube-kubelet`

-rwxr-xr-x. 2 root root 129M Jan  1  1970 /usr/bin/kube-apiserver -rwxr-xr-x. 2 root root 114M Jan  1  1970 /usr/bin/kube-controller-manager -rwxr-xr-x. 2 root root  54M Jan  1  1970 /usr/bin/kube-scheduler -rwxr-xr-x. 2 root root 105M Jan  1  1970 /usr/bin/kubelet -rwxr-xr-x. 2 root root 3.5K Jan  1  1970 /usr/bin/kubensenter

Should save about 297M or 74% in most environments where the kubelet is all that's desired.

It's not clear to me why these were ever in the RPM since OCP 4.x but this packaging should remain compatible

2024-02-13 19:50 UTC, sdodson commented on openshift.spec
>  Requires:       iptables
Hmm, these probably need to move to openshift-hyperkube-kubelet sub-package

2024-02-14 14:47 UTC, travier reviewed
/lgtm

2024-02-14 14:47 UTC, travier requested changes
/lgtm

2024-02-14 16:38 UTC, sdodson commented
/cc @mrunalp @soltysh 
Do you mind reviewing this, I believe it's ready to go after some testing upgrading from old package format to new format.

2024-02-14 16:39 UTC, soltysh approved these changes
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

2024-02-14 16:40 UTC, rphillips commented
/lgtm

2024-02-14 18:36 UTC, sdodson commented
/hold
Needs changes to release repo to ensure that all of the rpms are available https://github.com/openshift/release/pull/48807

2024-02-19 18:36 UTC, rphillips commented
/retest-required
/hold cancel

2024-02-19 23:43 UTC, sdodson commented
/retest

2024-02-21 20:53 UTC, merged

2024-03-11 01:33 UTC, sdodson commented
/cherry-pick release-4.15