WIP: poc: OIDC patch for restrictusers
openshift/kubernetes pull request #2157
Opened 2024-12-09 20:20 UTC by everettraven

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2025-01-09 20:59 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> +				if auth.Spec.Type == configv1.AuthenticationTypeOIDC {
Probably want something a bit more robust than just checking this. May be able to have this check the configuration to see if it should be running in OIDC mode.

2025-01-30 21:41 UTC, everettraven commented
/retest-required

2025-02-11 13:46 UTC, everettraven commented
/retest

2025-02-14 11:40 UTC, liouk requested changes

2025-02-14 11:40 UTC, liouk commented on openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
> +	}
Would something like this for error handling be appropriate here?
```suggestion
	if err := userInformers.User().V1().Groups().Informer().AddIndexers(cache.Indexers{
		usercache.ByUserIndexName: usercache.ByUserIndexKeys,
	}); err != nil {
		utilruntime.HandleError(err)
		return
	}
```

2025-02-14 19:05 UTC, everettraven commented on openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
> +	}
Updated in the latest push

2025-02-17 13:15 UTC, everettraven commented
/retest-required

2025-02-28 15:33 UTC, liouk commented
/lgtm

2025-03-11 15:19 UTC, bertinatto commented on openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
> +		return
This is how we're handling errors in other places in this file, so this seems correct because this is an admission plugin, i.e., it's a non-user-facing error.

2025-03-11 15:19 UTC, bertinatto commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
In the enhancement, you have this:

```
- `Group` informer creation and configuration is moved into the `authorization.openshift.io/RestrictSubjectBindings` admission plugin initialization process
```

From what I understand from your PR, you are not moving the **creation** of the informer, only the indexer is being added in the admission plugin's informer instead. I assume that's what you meant by "configuration" (i.e., the indexer).

However, in the PR description, you said:

```
(...)
This is necessary to prevent the startup of an informer for the Group API when the plugin is disabled
(...)
```

So I'm wondering how this is preventing the startup of the informer. It seems to me that it's still being started as before. Am I missing anything?

2025-03-11 18:59 UTC, benluddy commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
The object passed to the admission plugin initializer is an informer factory, and it's the chained call to `Informer()` that both creates and registers a new informer if needed (and the informer is later started by SharedInformerFactory's Start). So moving that call to plugin initialization instead of run-always should actually work. This all assumes that the one call being moved is the only place a User informer is being requested.

2025-03-11 19:02 UTC, benluddy commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
https://github.com/openshift/kubernetes/blob/2f2cf3874c491fae316a4537b274f31ec899dc05/vendor/github.com/openshift/client-go/user/informers/externalversions/factory.go#L162-L184

2025-03-11 19:16 UTC, benluddy commented on openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
> +func newOAuthAPIServiceReachabilityCheck(ipForKubernetesDefaultService net.IP) *aggregatedAPIServiceAvailabilityCheck {
I'd like to see the cosmetic changes excluded to reduce the potential for conflicts as we maintain this patch over the years.

2025-03-11 19:17 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
It was the only place for that particular `SharedInformerFactory` that it was being called

2025-03-11 19:19 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
> +func newOAuthAPIServiceReachabilityCheck(ipForKubernetesDefaultService net.IP) *aggregatedAPIServiceAvailabilityCheck {
This one was my doing, the rest were `go fmt` related. I'm happy to revert cosmetic changes, would you like both this and the `go fmt` changes reverted?

2025-03-11 19:56 UTC, benluddy commented on openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
> +func newOAuthAPIServiceReachabilityCheck(ipForKubernetesDefaultService net.IP) *aggregatedAPIServiceAvailabilityCheck {
I don't see any output if I run gofmt -d on either of the other files. Is it me? Maybe your editor is set up to run a gofmt-alike? I'd remove all of the cosmetic changes.

2025-03-11 20:35 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
> +func newOAuthAPIServiceReachabilityCheck(ipForKubernetesDefaultService net.IP) *aggregatedAPIServiceAvailabilityCheck {
What version of Go are you running?

2025-03-11 20:44 UTC, benluddy commented on openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
> +func newOAuthAPIServiceReachabilityCheck(ipForKubernetesDefaultService net.IP) *aggregatedAPIServiceAvailabilityCheck {
I ran `GOTOOLCHAIN=go1.23.4 go fmt openshift-kube-apiserver/openshiftkubeapiserver/patch.go` on master and it didn't make any changes.

2025-03-11 23:13 UTC, bertinatto commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
Hm, I see. Thanks for the explanation. So the factory is created in the run-always path, and the informers that are requested are started there as well. However, the creation of the informer and its configuration **need** to be done in the plugin.

I'm not familiar with this, and maybe that's how it's typically done, but this "shared responsibility" over the informer sounds error-prone to me. Is there a way to keep where it is, but run it conditionally?

Regardless, if we're going to do this, I'd suggest adding a comment in the plugin initialization stating that. Also, do we have a job proving this is working as intended?

2025-03-12 15:06 UTC, benluddy commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
> Is there a way to keep where it is, but run it conditionally?

This is typical. Take a look at all of the implementations of this: https://github.com/openshift/kubernetes/blob/2f2cf3874c491fae316a4537b274f31ec899dc05/staging/src/k8s.io/apiserver/pkg/admission/initializer/interfaces.go#L40

The part that is atypical is having only one thing that requires a Group informer, and that it happens to be an admission plugin that is not always enabled. I agree there should be some job demonstrating that this is doing what we expect (are we looking to see that there are group watch 404s from kube-apiserver in an E2E job that enables and disables external OIDC without this, and that those requests disappear with this patch?).

Is there something we could add to CI that would tell us when we have perma-unstarted informers? I know that it's one of the /readyz checks to wait for all the Kube shared informers to start (https://github.com/openshift/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/config.go#L960-L976). I guess we can't do the same for resources served by the aggregation layer without having a chicken-and-egg problem. Still, we should emit some indication that can be wired to a monitor test.

2025-03-12 15:15 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
There is not an existing CI job to test this behavior, but is one that is intended to be created. If this PR is not mergeable until such a job exists I'm happy to place this PR on hold until then. 

I _have_ manually tested this based on https://issues.redhat.com/browse/OCPBUGS-45460 and verified that disabling the admission plugin does not result in seeing the same reflector errors being logged. I know manual testing isn't a good substitute for a repeatable CI job, but thought it was worth mentioning that I least stood up a cluster and manually tested this.

2025-03-12 15:21 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
> +func newOAuthAPIServiceReachabilityCheck(ipForKubernetesDefaultService net.IP) *aggregatedAPIServiceAvailabilityCheck {
Cosmetic changes reverted

2025-03-12 15:21 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
> +func newOAuthAPIServiceReachabilityCheck(ipForKubernetesDefaultService net.IP) *aggregatedAPIServiceAvailabilityCheck {
Will rebase to roll up the commit that reverts it in a bit.

2025-03-12 15:30 UTC, everettraven commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
This isn't critical, and the BYO OIDC functionality is now slated for TP in 4.19, so this PR can wait until we've got more progress done on the testing front for that feature.

2025-03-12 21:19 UTC, bertinatto commented on openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> -	}
> This is typical. Take a look at all of the implementations of this: 

Thank you, now I see.

Another question: don't we need to wait for the cache to warm up?

```diff
diff --git i/openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go w/openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
index 4dea00e61a4..e37ef8c0ff0 100644
--- i/openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
+++ w/openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
@@ -88,13 +88,16 @@ func (q *restrictUsersAdmission) SetRESTClientConfig(restClientConfig rest.Confi
 }
 
 func (q *restrictUsersAdmission) SetUserInformer(userInformers userinformer.SharedInformerFactory) {
-	if err := userInformers.User().V1().Groups().Informer().AddIndexers(cache.Indexers{
+	groupInformer := userInformers.User().V1().Groups()
+	if err := groupInformer.Informer().AddIndexers(cache.Indexers{
 		usercache.ByUserIndexName: usercache.ByUserIndexKeys,
 	}); err != nil {
 		utilruntime.HandleError(err)
 		return
 	}
-	q.groupCache = usercache.NewGroupCache(userInformers.User().V1().Groups())
+	q.groupCache = usercache.NewGroupCache(groupInformer)
+
+	q.SetReadyFunc(groupInformer.Informer().HasSynced)
 }
 
 // subjectsDelta returns the relative complement of elementsToIgnore in
@@ -129,6 +132,10 @@ func (q *restrictUsersAdmission) Validate(ctx context.Context, a admission.Attri
 		return nil
 	}
 
+	if !q.WaitForReady() {
+		return admission.NewForbidden(a, fmt.Errorf("not yet ready to handle request"))
+	}
+
 	// Ignore all operations that correspond to subresource actions.
 	if len(a.GetSubresource()) != 0 {
 		return nil
```

2025-06-12 12:05 UTC, everettraven commented
/remove-lifecycle stale
/lifecycle frozen

2025-08-11 12:18 UTC, liouk commented
/validate-backports

2025-08-11 12:39 UTC, bertinatto reviewed
To make rebases less painful, please amend the commit message to specify which existing carry patch this should be squashed into.

Also, do we have a openshift/origin test that validates this change?

2025-08-11 13:16 UTC, benluddy commented on openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
> +		return
The existing behavior prevents kube-apiserver from starting. You could surface this error through the return value of ValidateInitialization?

2026-04-04 08:07 UTC, closed without merging