Addresses build error pause
openshift/kubernetes pull request #685
Opened 2021-04-20 09:20 UTC by joepvd

Ensuring the target directory exists before writing a file to it.

/kind bug

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-04-20 13:54 UTC, joepvd commented
/retest

2021-04-20 14:06 UTC, joepvd commented
/bugzilla refresh

2021-04-20 14:43 UTC, soltysh requested changes
Rename the commit to:
`UPSTREAM: <carry>: Add Dockerfile to build pause image`
so that during next k8s bump we squash this commit with the other one.

2021-04-20 15:47 UTC, joepvd commented
/bugzilla refresh

2021-04-20 19:29 UTC, joepvd commented
/retest

2021-04-21 04:44 UTC, joepvd commented
/retest

2021-04-21 07:15 UTC, joepvd commented
/retest

2021-04-21 10:45 UTC, joepvd commented
/retest

2021-04-21 13:44 UTC, joepvd commented
/test e2e-gcp-upgrade

2021-04-21 17:39 UTC, umohnani8 commented
LGTM
/retest

2021-04-21 22:18 UTC, joepvd commented
/retest

2021-04-22 05:34 UTC, joepvd commented
/retest

2021-04-22 08:22 UTC, joepvd commented
/retest

2021-04-22 10:53 UTC, joepvd commented
/test e2e-gcp-upgrade

2021-04-22 11:29 UTC, joepvd commented
/test e2e-agnostic-cmd

2021-04-22 15:19 UTC, joepvd commented
/retest

2021-04-22 18:52 UTC, joepvd commented
/retest

2021-04-23 07:46 UTC, joepvd commented
/retest

2021-04-23 11:27 UTC, joepvd commented
/retest

2021-04-23 18:28 UTC, yselkowitz commented
This is blocking the build of pod.
/lgtm
/assign @sttts

2021-04-26 12:50 UTC, soltysh approved these changes
/approve

2021-04-26 19:37 UTC, joepvd commented
/retest

2021-04-27 11:48 UTC, joepvd commented
/assign @sttts

2021-04-27 15:43 UTC, joepvd commented
/retest

2021-04-27 23:33 UTC, yselkowitz commented
ose-pod has not built successfully in 4.8 for two weeks now, please expedite.

2021-04-28 11:06 UTC, soltysh commented
This is unblocking nightly builds and doesn't change functionality 

/override ci/prow/e2e-aws-fips
/override ci/prow/k8s-e2e-gcp
/override ci/prow/e2e-gcp-upgrade

2021-04-28 22:58 UTC, yselkowitz commented
/retest

2021-04-29 08:21 UTC, joepvd commented
/retest

2021-04-29 10:01 UTC, joepvd commented
/retest

2021-04-29 12:54 UTC, joepvd commented
/retest

2021-04-29 14:54 UTC, joepvd commented
Could the failing tests be overridden? Think it'd be good to have an updated image in the upcoming fc.

2021-04-30 00:05 UTC, merged